import "@repo/ui/globals.css";
import { Toaster } from "@ui/components/ui/toaster";
import type { Metadata } from "next";
import { ThemeProvider } from "./components/theme-provider";
export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="ko">
      <head />
      <body className="scrollbar-hide">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
